### ISSUE TITLE
Bug with dbusProxy on diya-node-status in diya-node-action

### ISSUE THREAD

**Issue by FredericAMAN** [partnering/node-dbus#16]
@nschoe 
Errors when starts service action before service status or when restarts service status.

To reproduce the bug, use branch master for diya-node-action and branch 96-dbus for diya-node-status.

When starts diya-node-action before diya-node-status:
```
diya@e1fa2f112ca9:/usr/lib/diya-node-action$ node .
Service exposed and ready to answer calls, with name 'fr.partnering.Action'
Could not introspect object '/fr/partnering/Status/Robots' of service 'fr.partnering.Status'
Error: path E1fa2f112ca9 already exists
    at DBusObject.addObject (/usr/lib/diya-node-action/node_modules/dbus-native/lib/DBusObjectLibs.js:194:10)
    at Promise.promisify.then.then.introspectData (/usr/lib/diya-node-action/node_modules/dbus-native/lib/DBusProxy.js:610:13)
    at tryCatcher (/usr/lib/diya-node-action/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/lib/diya-node-action/node_modules/bluebird/js/release/promise.js:636:18)
    at Object.<anonymous> (/usr/lib/diya-node-action/node_modules/bluebird/js/release/nodeback.js:42:21)
    at EventEmitter.<anonymous> (/usr/lib/diya-node-action/node_modules/dbus-native/lib/bus.js:207:31)
[INFO] Service Status connected
```

When restarts diya-node-status when diya-node-action is already started:
```
diya@e1fa2f112ca9:/usr/lib/diya-node-action$ node .
Service exposed and ready to answer calls, with name 'fr.partnering.Action'
[INFO] Service Status connected
[INFO] Service Status disconnected
[INFO] Service Status connected
Error: interface 'fr.partnering.Status.Part' doesn't have a property 'Time'; dropping 'PropertiesChanged'.
Error: interface 'fr.partnering.Status.Part' doesn't have a property 'Code'; dropping 'PropertiesChanged'.
Error: interface 'fr.partnering.Status.Part' doesn't have a property 'CodeRef'; dropping 'PropertiesChanged'.
Error: interface 'fr.partnering.Status.Part' doesn't have a property 'Category'; dropping 'PropertiesChanged'.
Error: interface 'fr.partnering.Status.Part' doesn't have a property 'PartName'; dropping 'PropertiesChanged'.
Error: interface 'fr.partnering.Status.Part' doesn't have a property 'Msg'; dropping 'PropertiesChanged'.
Error: interface 'fr.partnering.Status.Part' doesn't have a property 'CritLevel'; dropping 'PropertiesChanged'.
Error: interface 'fr.partnering.Status.Part' doesn't have a property 'Description'; dropping 'PropertiesChanged'.
Unhandled rejection (<Connection ":1.429" is not allowed to ...>, no stack trace)

Unhandled rejection (<Connection ":1.429" is not allowed to ...>, no stack trace)

Unhandled rejection (<Connection ":1.429" is not allowed to ...>, no stack trace)

Unhandled rejection (<Connection ":1.429" is not allowed to ...>, no stack trace)

Unhandled rejection (<Connection ":1.429" is not allowed to ...>, no stack trace)

Unhandled rejection (<Connection ":1.429" is not allowed to ...>, no stack trace)

Unhandled rejection (<Connection ":1.429" is not allowed to ...>, no stack trace)

Unhandled rejection (<Connection ":1.429" is not allowed to ...>, no stack trace)

Unhandled rejection (<Connection ":1.429" is not allowed to ...>, no stack trace)

Unhandled rejection (<Connection ":1.429" is not allowed to ...>, no stack trace)


```

**Comment by nschoe** [comment]
@FredericAMAN does this problem still occur?
