### ISSUE TITLE
huge stack trace when creating a proxy on NetworkManager

### ISSUE THREAD

**Issue by nilpotence** [partnering/node-dbus#17]
I'm trying to create a proxy on network-manager as follow :
call.js : 
```js
const dbus = require('dbus-native')
const inspect = require('util').inspect
const Promiser = require('bluebird')

const bus = dbus.systemBus()

bus.on('ready', () => {
	const proxy = bus.mkProxy('org.freedesktop.NetworkManager')
	proxy.on('connected', nm => {
		console.log('proxy connected')
	})
})
```

However when I execute the above code, I get a huge stack trace :

```bash
$ sudo node call.js
...
    at fromOldToNewAPI (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:227:18)
    at vals.map (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:240:35)
    at Array.map (native)
    at fromOldToNewAPI (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:240:18)
    at vals.map.e (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:227:28)
    at Array.map (native)
    at fromOldToNewAPI (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:227:18)
    at fromOldToNewAPI (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:255:19)
    at vals.reduce (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:210:14)
    at Array.reduce (native)
    at Object.fromOldToNewAPI (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:208:18)
    at getAllCalls.push.Promise.promisify.then.ret (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/DBusProxy.js:362:33)
    at tryCatcher (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/node_modules/bluebird/js/release/promise.js:636:18)
    at Object.<anonymous> (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/node_modules/bluebird/js/release/nodeback.js:42:21)
    at EventEmitter.<anonymous> (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/bus.js:207:31)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
Could not introspect object '/org/freedesktop/NetworkManager/IP6Config/16' of service 'org.freedesktop.NetworkManager'
TypeError: vals.map is not a function
    at fromOldToNewAPI (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:227:18)
    at vals.map (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:240:35)
    at Array.map (native)
    at fromOldToNewAPI (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:240:18)
    at vals.map.e (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:227:28)
    at Array.map (native)
    at fromOldToNewAPI (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:227:18)
    at fromOldToNewAPI (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:255:19)
    at vals.reduce (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:210:14)
    at Array.reduce (native)
    at Object.fromOldToNewAPI (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/utils.js:208:18)
    at getAllCalls.push.Promise.promisify.then.ret (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/lib/DBusProxy.js:362:33)
    at tryCatcher (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/sylvmahe/junk/dbuscall/node_modules/dbus-native/node_modules/bluebird/js/release/promise.js:510:31)
...
proxy connected
...
Error: interface 'org.freedesktop.NetworkManager.AccessPoint' doesn't have a property 'Strength'; dropping 'PropertiesChanged'.
Error: Malformed or badly-parsed 'ChangedProperties' payload!
Error: interface 'org.freedesktop.NetworkManager.AccessPoint' doesn't have a property 'Strength'; dropping 'PropertiesChanged'.
Error: Malformed or badly-parsed 'ChangedProperties' payload!
Error: interface 'org.freedesktop.NetworkManager.AccessPoint' doesn't have a property 'Strength'; dropping 'PropertiesChanged'.
Error: Malformed or badly-parsed 'ChangedProperties' payload!
Error: Malformed or badly-parsed 'ChangedProperties' payload!
Error: interface 'org.freedesktop.NetworkManager.AccessPoint' doesn't have a property 'Strength'; dropping 'PropertiesChanged'.
Error: Malformed or badly-parsed 'ChangedProperties' payload!
```

**Comment by nilpotence** [comment]
@nschoe

**Comment by nschoe** [comment]
Issue closed in branch DBusProxy
