### ISSUE TITLE
Obscure error message when trying to expose a service whose name is already taken

### ISSUE THREAD

**Issue by nilpotence** [partnering/node-dbus#24]
When trying to start a service with name ```foo.bar```, if the name is already reserved, we get the following error : 
```
And error was returned as a string, re-throwing it as a proper Error, but it should be fixed.
Unhandled rejection Error: Failed to exposed service on bus: Error: 3
    at systemBus.exposeService.then.catch (/usr/lib/diya-node-ieq-input/src/main.js:43:8)
    at tryCatcher (/usr/lib/diya-node-ieq-input/node_modules/dbus-native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/diya-node-ieq-input/node_modules/dbus-native/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/diya-node-ieq-input/node_modules/dbus-native/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/diya-node-ieq-input/node_modules/dbus-native/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/diya-node-ieq-input/node_modules/dbus-native/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/lib/diya-node-ieq-input/node_modules/dbus-native/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/lib/diya-node-ieq-input/node_modules/dbus-native/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/lib/diya-node-ieq-input/node_modules/dbus-native/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5) 
```

It would be nice to have a more explicit error message than ``` Error 3 ```. 

(And if you are going to be obscur and stuff, at least do it well : ```Error at register 0x00340ad3f. Kernel Panic. DefCon 1 activated```)

**Comment by nschoe** [comment]
Weeeeeeell I don't find this error message obscure, I mean... _everybody_ should know that `Error 3` actually means

> I'm sorry dear gentleman, but the DBus service name which you are currently trying to register (excellent choice on this name, by the way, it suits you perfectly!) is unfortunately already taken by _another_ process. I strongly suggest that you reach out to it and try to to negotiate a safe and peaceful release, because frankly, I believe _you_ should own the name.

But okay, if it's not obvious, I'll change the error message :)

@nilpotence

**Comment by nschoe** [comment]
Issue closed in branch DBusProxy
